apiVersion: v1
kind: ConfigMap
metadata:
  name: subway-monitor-config
  namespace: subway-monitor
data:
  POSTGRES_HOST: "timescaledb-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "subway_monitor"
  REDIS_URL: "redis://redis-service:6379/0"
  FEED_UPDATE_INTERVAL: "30"
  MODEL_RETRAIN_HOUR: "3"
  ANOMALY_CONTAMINATION: "0.05"